### ISSUE TITLE
how to generate the pkl?

### ISSUE THREAD

**Issue by shanhaidexiamo** [yluo42/TAC#5]
Hi, I find the data generation part needs to read the pkl file , but if I want to modify the room size and num of mics, how to generate pkl? Does this mean that I need to manually modify the pkl file you provided?

**Comment by framsc** [comment]
I guess that the pkl files are generated with random parameters using a python script. Do not manually modify the pkl files. Write codes to generate them.

**Comment by shanhaidexiamo** [comment]
> I guess that the pkl files are generated with random parameters using a python script. Do not manually modify the pkl files. Write codes to generate them.

yes. I think so. the code is incomplete, hope author can open more code

**Comment by yluo42** [comment]
You should not modify the .pkl config files in order to correctly generate the dataset. data/create_dataset.py should be a complete file for generating the data.

If you want to create your own data (for data augmentation or other purposes), you can take a look at the items in the configurations and randomly generate more. Also take a look at data/create_dataset.py to see how the config files are used, e.g. the items in the .pkl files.
